version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  airflow:
    image: apache/airflow:2.9.2-python3.11
    container_name: airflow
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: "False"
      AIRFLOW_HOME: /opt/airflow

      # Airflow metadata DB connection (uses the same Postgres service)
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      # Create a usable Airflow connection string for our target DB
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      # App-specific env vars
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
      STOCK_SYMBOLS: ${STOCK_SYMBOLS}
      OUTPUT_SIZE: ${OUTPUT_SIZE}
    ports:
      - "8080:8080"   # Airflow Web UI
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: >
      bash -lc "
      airflow db migrate &&
      (airflow users list | grep -q admin@local || airflow users create
        --username admin --firstname Admin --lastname User
        --role Admin --email admin@local --password admin) &&
      airflow scheduler & airflow webserver
      "

volumes:
  pgdata:
